settings:
  plugin:
    update_check: true
    enable_placeholderapi: false
    bungee:
      enable: false
      connect_to_hub: true
      hub: 'lobbyserver'
      shutdown_when_game_ends: true
  game:
    min_players: 3
    max_players: 50
    announcements: true
    seconds_for_each_minigame: 60
  rewards:
    credits:
      enable: true
      use_economy: false
      max_amount: 30
      min_amount: 10
    items:
      enable: false
      item_id: 264
      max_amount: 10
      min_amount: 3